- name: Playbook to copy a file to target machines
  hosts: controllers
  tasks:
    - name: Copy the file test.txt to target machine
      copy:
        src: /tmp/test.txt
        dest: /var/tmp/test.txt
