- name: "Remove the package: {{ item.name }}"
  yum:
    name: "{{ item.name }}"
    state: absent
  when: ansible_facts.os_family == "RedHat" and item.status == "absent"
  become: yes

- name: "Install the Package: {{ item.name }}"
  yum:
    name: "{{ item.name }}"
    state: present
  when: ansible_facts.os_family == "RedHat" and item.status == "present"
  become: yes
